name: publish
env:
  CI: true
on:
  push:
    branches:
      - main
    tags:
      - "!*"
permissions:
  contents: read
  packages: write
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 24.7.0
          registry-url: 'https://npm.pkg.github.com'
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish --registry https://npm.pkg.github.com --access restricted || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}